name: MacOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install autotools
      run: brew install autoconf automake libtool binutils

    - name: autoconf
      run: autoconf

    - name: configure
      run: sudo ./configure

    - name: make sharedlib
      run: make sharedlib

    - name: make install
      run: make install
  
    - name: make tests
      run: make tests

    - name: run tests
      run: ./bin/testsuite